-- Room to Tracker Map
RoomToMap = {
    [23]  = {"World Map"},  -- Main Menu
    [382] = {"World Map"},  -- Airship Menu

    -- [368] = {"Dream Zanarkand"},
    -- [376] = {"Dream Zanarkand"},
    -- [371] = {"Dream Zanarkand"},
    -- [370] = {"Dream Zanarkand"},
    -- [366] = {"Dream Zanarkand"},
    -- [389] = {"Dream Zanarkand"},
    -- [367] = {"Dream Zanarkand"},
    -- [384] = {"Dream Zanarkand"},
    -- [385] = {"Dream Zanarkand"},

    [48]  = {"Baaj Temple", "Baaj Temple"},
    [49]  = {"Baaj Temple", "Baaj Temple"},
    [50]  = {"Baaj Temple", "Baaj Temple"},
    [63]  = {"Baaj Temple", "Baaj Temple"},
    [52]  = {"Baaj Temple", "Baaj Temple"},
    [74]  = {"Baaj Temple", "Baaj Temple"},
    [295] = {"Baaj Temple", "Baaj Temple"},
    [196] = {"Baaj Temple", "Baaj Temple"},
    [298] = {"Baaj Temple", "Baaj Temple"},
    [51]  = {"Baaj Temple", "Baaj Temple"},
    [71]  = {"Baaj Temple", "Al Bhed Ship"},
    [288] = {"Baaj Temple", "Al Bhed Ship"},
    [64]  = {"Baaj Temple", "Al Bhed Ship"},
    [380] = {"Baaj Temple", "Al Bhed Ship"},

    [70]  = {"Besaid", "Island"},
    [20]  = {"Besaid", "Island"},
    [41]  = {"Besaid", "Island"},
    [67]  = {"Besaid", "Island"},
    [69]  = {"Besaid", "Island"},
    [133] = {"Besaid", "Village"},
    [17]  = {"Besaid", "Village"},
    [142] = {"Besaid", "Village"},
    [144] = {"Besaid", "Village"},
    [145] = {"Besaid", "Village"},
    [60]  = {"Besaid", "Village"},
    [143] = {"Besaid", "Village"},
    [84]  = {"Besaid", "Village"},
    [42]  = {"Besaid", "Temple"},
    [147] = {"Besaid", "Temple"},
    [146] = {"Besaid", "Temple"},
    [122] = {"Besaid", "Temple"},
    [103] = {"Besaid", "Temple"},
    [83]  = {"Besaid", "Village"},
    [100] = {"Besaid", "Village"},
    [252] = {"Besaid", "Village"},
    [68]  = {"Besaid", "Village"},
    [117] = {"Besaid", "Village"},
    [21]  = {"Besaid", "Island"},
    [22]  = {"Besaid", "Island"},
    [19]  = {"Besaid", "Island"},
    [301] = {"Besaid", "S.S. Liki"},
    [148] = {"Besaid", "S.S. Liki"},
    [149] = {"Besaid", "S.S. Liki"},
    [150] = {"Besaid", "S.S. Liki"},
    [154] = {"Besaid", "S.S. Liki"},
    [61]  = {"Besaid", "S.S. Liki"},
    [282] = {"Besaid", "S.S. Liki"},
    [220] = {"Besaid", "S.S. Liki"},
    [139] = {"Besaid", "S.S. Liki"},

    [43]  = {"Kilika", "Village & Woods"},
    [53]  = {"Kilika", "Village & Woods"},
    [152] = {"Kilika", "Village & Woods"},
    [46]  = {"Kilika", "Village & Woods"},
    [16]  = {"Kilika", "Village & Woods"},
    [151] = {"Kilika", "Village & Woods"},
    [293] = {"Kilika", "Village & Woods"},
    [98]  = {"Kilika", "Village & Woods"},
    [47]  = {"Kilika", "Village & Woods"},
    [166] = {"Kilika", "Village & Woods"},
    [294] = {"Kilika", "Village & Woods"},
    [18]  = {"Kilika", "Village & Woods"},
    [65]  = {"Kilika", "Village & Woods"},
    [78]  = {"Kilika", "Temple"},
    [155] = {"Kilika", "Temple"},
    [156] = {"Kilika", "Temple"},
    [96]  = {"Kilika", "Temple"},
    [44]  = {"Kilika", "Temple"},
    [108] = {"Kilika", "Temple"},
    [45]  = {"Kilika", "Temple"},
    [297] = {"Kilika", "Temple"},
    [118] = {"Kilika", "Temple"},
    -- [94]  = {"Kilika", "S.S. Winno"},
    -- [167] = {"Kilika", "S.S. Winno"},
    -- [237] = {"Kilika", "S.S. Winno"},
    -- [168] = {"Kilika", "S.S. Winno"},
    -- [169] = {"Kilika", "S.S. Winno"},
    -- [191] = {"Kilika", "S.S. Winno"},
    -- [185] = {"Kilika", "S.S. Winno"},
    -- [302] = {"Kilika", "S.S. Winno"},

    -- [267] = {"Luca", "Dock"},
    -- [377] = {"Luca", "Dock"},
    -- [268] = {"Luca", "Dock"},
    -- [355] = {"Luca", "Dock"},
    -- [72]  = {"Luca", "Dock"},
    -- [123] = {"Luca", "Stadium"},
    -- [73]  = {"Luca", "Stadium"},
    -- [85]  = {"Luca", "Dock"},
    -- [86]  = {"Luca", "Dock"},
    -- [87]  = {"Luca", "Dock"},
    -- [88]  = {"Luca", "Dock"},
    -- [89]  = {"Luca", "Dock"},
    -- [77]  = {"Luca", "City"},
    -- [157] = {"Luca", "City"},
    -- [170] = {"Luca", "City"},
    -- [158] = {"Luca", "City"},
    -- [184] = {"Luca", "City"},
    -- [104] = {"Luca", "City"},
    -- [107] = {"Luca", "City"},
    -- [121] = {"Luca", "City"},
    -- [159] = {"Luca", "City"},
    -- [299] = {"Luca", "Dock"},
    -- [113] = {"Luca", "Dock"},
    -- [124] = {"Luca", "Stadium"},
    -- [62]  = {"Luca", "Stadium"},
    -- [212] = {"Luca", "Stadium"},
    -- [347] = {"Luca", "Stadium"},
    -- [250] = {"Luca", "Stadium"},
    -- [125] = {"Luca", "Stadium"},
    -- [57]  = {"Luca", "Stadium"},
    -- [55]  = {"Luca", "Stadium"},

    -- [95]  = {"Miihen Highroad", "South & Central"},
    -- [120] = {"Miihen Highroad", "South & Central"},
    -- [127] = {"Miihen Highroad", "South & Central"},
    -- [58]  = {"Miihen Highroad", "Agency"},
    -- [171] = {"Miihen Highroad", "Agency"},
    -- [112] = {"Miihen Highroad", "Agency"},
    -- [115] = {"Miihen Highroad", "North"},
    -- [116] = {"Miihen Highroad", "North"},
    -- [59]  = {"Miihen Highroad", "North"},

    -- [79]  = {"Mushroom Rock Road", "Entrance"},
    -- [92]  = {"Mushroom Rock Road", "Valley"},
    -- [128] = {"Mushroom Rock Road", "Precipice"},
    -- [119] = {"Mushroom Rock Road", "Ridge"},
    -- [247] = {"Mushroom Rock Road", "Ridge"},
    -- [254] = {"Mushroom Rock Road", "Ridge"},
    -- [218] = {"Mushroom Rock Road", "Ridge"},
    -- [341] = {"Mushroom Rock Road", "Ridge"},
    -- [289] = {"Mushroom Rock Road", "Ridge"},
    -- [131] = {"Mushroom Rock Road", "Aftermath"},

    -- [93]  = {"Djose", "Highroad"},
    -- [76]  = {"Djose", "Pilgrimage Road"},
    -- [82]  = {"Djose", "Temple"},
    -- [210] = {"Djose", "Temple"},
    -- [81]  = {"Djose", "Temple"},
    -- [161] = {"Djose", "Temple"},
    -- [160] = {"Djose", "Temple"},
    -- [214] = {"Djose", "Temple"},
    -- [90]  = {"Djose", "Temple"},
    -- [91]  = {"Djose", "Temple"},
    -- [245] = {"Djose", "Temple"},

    [75]  = {"Moonflow"},
    [105] = {"Moonflow"},
    [187] = {"Moonflow"},
    [188] = {"Moonflow"},
    [234] = {"Moonflow"},
    [235] = {"Moonflow"},
    [99]  = {"Moonflow"},
    [291] = {"Moonflow"},
    [236] = {"Moonflow"},
    [190] = {"Moonflow"},
    [189] = {"Moonflow"},
    [109] = {"Moonflow"},
    [97]  = {"Moonflow"},

    [135] = {"Guadosalam"},
    [243] = {"Guadosalam"},
    [174] = {"Guadosalam"},
    [173] = {"Guadosalam"},
    [172] = {"Guadosalam"},
    [163] = {"Guadosalam"},
    [141] = {"Guadosalam"},
    [197] = {"Guadosalam"},
    [217] = {"Guadosalam"},
    [175] = {"Guadosalam"},
    [257] = {"Guadosalam"},
    [193] = {"Guadosalam"},
    [364] = {"Guadosalam"},
    [213] = {"Guadosalam"},

    [140] = {"Thunder Plains"},
    [256] = {"Thunder Plains"},
    [263] = {"Thunder Plains"},
    [264] = {"Thunder Plains"},
    [262] = {"Thunder Plains"},
    [162] = {"Thunder Plains"},

    -- [110] = {"Macalania", "Woods"},
    -- [241] = {"Macalania", "Woods"},
    -- [242] = {"Macalania", "Woods"},
    -- [221] = {"Macalania", "Woods"},
    -- [248] = {"Macalania", "Woods"},
    -- [330] = {"Macalania", "Woods"},
    -- [331] = {"Macalania", "Woods"},
    -- [391] = {"Macalania", "Woods"},
    -- [164] = {"Macalania", "Woods"},
    -- [215] = {"Macalania", "Woods"},
    -- [102] = {"Macalania", "Lake"},
    -- [192] = {"Macalania", "Lake"},
    -- [153] = {"Macalania", "Lake"},
    -- [106] = {"Macalania", "Lake"},
    -- [178] = {"Macalania", "Lake"},
    -- [179] = {"Macalania", "Lake"},
    -- [239] = {"Macalania", "Lake"},
    -- [80]  = {"Macalania", "Lake"},
    -- [284] = {"Macalania", "Lake"},
    -- [365] = {"Macalania", "Lake"},
    -- [54]  = {"Macalania", "Lake"},
    -- [260] = {"Macalania", "Lake"},

    [129] = {"Bikanel", "Desert"},
    [136] = {"Bikanel", "Desert"},
    [137] = {"Bikanel", "Desert"},
    [138] = {"Bikanel", "Desert"},
    [130] = {"Bikanel", "Home"},
    [276] = {"Bikanel", "Home"},
    [280] = {"Bikanel", "Home"},
    [286] = {"Bikanel", "Home"},
    [275] = {"Bikanel", "Home"},
    [219] = {"Bikanel", "Home"},
    [303] = {"Bikanel", "Home"},
    [261] = {"Bikanel", "Home"},

    [194] = {"Airship"},
    [265] = {"Airship"},
    [351] = {"Airship"},
    [211] = {"Airship"},
    [277] = {"Airship"},
    [255] = {"Airship"},
    [392] = {"Airship"},
    [199] = {"Airship"},
    [200] = {"Airship"},
    [201] = {"Airship"},
    [374] = {"Airship"},
    [375] = {"Airship"},
    [202] = {"Airship"},

    [205] = {"Bevelle", "Bevelle"},
    [180] = {"Bevelle", "Bevelle"},
    [181] = {"Bevelle", "Bevelle"},
    [182] = {"Bevelle", "Bevelle"},
    [306] = {"Bevelle", "Bevelle"},
    [226] = {"Bevelle", "Bevelle"},
    [198] = {"Bevelle", "Via Purifico"},
    [209] = {"Bevelle", "Via Purifico"},
    [208] = {"Bevelle", "Via Purifico"},
    [183] = {"Bevelle", "Via Purifico"},
    [274] = {"Bevelle", "Via Purifico"},
    [206] = {"Bevelle", "Via Purifico"},
    [177] = {"Bevelle", "Via Purifico"},
    [176] = {"Bevelle", "Via Purifico"},
    [329] = {"Bevelle", "Via Purifico"},
    [227] = {"Bevelle", "Bevelle"},
    [195] = {"Bevelle", "Bevelle"},
    [207] = {"Bevelle", "Bevelle"},
    [238] = {"Bevelle", "Bevelle"},
    [269] = {"Bevelle", "Bevelle"},
    [273] = {"Bevelle", "Bevelle"},
    [287] = {"Bevelle", "Bevelle"},
    [305] = {"Bevelle", "Bevelle"},

    [223] = {"Calm Lands", "Plains"},
    [290] = {"Calm Lands", "Remiem Temple"},
    [308] = {"Calm Lands", "Remiem Temple"},
    [372] = {"Calm Lands", "Remiem Temple"},
    [307] = {"Calm Lands", "Monster Arena"},
    [279] = {"Calm Lands", "Plains"},
    [266] = {"Calm Lands", "Plains"},
    [56]  = {"Calm Lands", "Cavern of the Stolen Fayth"},
    [283] = {"Calm Lands", "Cavern of the Stolen Fayth"},

    [259] = {"Mt. Gagazet", "Outside"},
    [244] = {"Mt. Gagazet", "Outside"},
    [285] = {"Mt. Gagazet", "Outside"},
    [309] = {"Mt. Gagazet", "Outside"},
    [165] = {"Mt. Gagazet", "Outside"},
    [249] = {"Mt. Gagazet", "Outside"},
    [272] = {"Mt. Gagazet", "Cave"},
    [310] = {"Mt. Gagazet", "Cave"},
    [311] = {"Mt. Gagazet", "Cave"},
    [312] = {"Mt. Gagazet", "Cave"},
    [361] = {"Mt. Gagazet", "Cave"},
    [362] = {"Mt. Gagazet", "Cave"},
    [381] = {"Mt. Gagazet", "Cave"},
    [383] = {"Mt. Gagazet", "Cave"},

    [132] = {"Zanarkand", "Ruins"},
    [363] = {"Zanarkand", "Ruins"},
    [225] = {"Zanarkand", "Ruins"},
    [314] = {"Zanarkand", "Ruins"},
    [222] = {"Zanarkand", "Ruins"},
    [316] = {"Zanarkand", "Ruins"},
    [313] = {"Zanarkand", "Ruins"},
    [320] = {"Zanarkand", "Temple"},
    [317] = {"Zanarkand", "Temple"},
    [318] = {"Zanarkand", "Temple"},
    [224] = {"Zanarkand", "Temple"},
    [270] = {"Zanarkand", "Temple"},
    [319] = {"Zanarkand", "Temple"},
    [315] = {"Zanarkand", "Ruins"},

    [322] = {"Inside Sin"},
    [203] = {"Inside Sin"},
    [296] = {"Inside Sin"},
    [204] = {"Inside Sin"},
    [327] = {"Inside Sin"},
    [324] = {"Inside Sin"},
    [325] = {"Inside Sin"},
    [326] = {"Inside Sin"},

    [258] = {"Omega Ruins"},
    [271] = {"Omega Ruins"},
}

function autoTab(value)
    if (RoomToMap[value] ~= nil) then   -- Map found, activate tab/s for room
        for _, tab in ipairs(RoomToMap[value]) do
            Tracker:UiHint("ActivateTab", tab)
        end
    else    -- If map not found, default to world map
        Tracker:UiHint("ActivateTab", "World Map")
    end
end


