Tracker:AddLocations("locations/Airship.json")
Tracker:AddLocations("locations/Al Bhed Primers.json")
Tracker:AddLocations("locations/Al Bhed Ship.json")
Tracker:AddLocations("locations/Baaj Temple.json")
Tracker:AddLocations("locations/Besaid.json")
Tracker:AddLocations("locations/Bevelle.json")
Tracker:AddLocations("locations/Bikanel.json")
Tracker:AddLocations("locations/Calm Lands.json")
Tracker:AddLocations("locations/Cavern of the Stolen Fayth.json")
Tracker:AddLocations("locations/Celestial.json")
Tracker:AddLocations("locations/Djose.json")
Tracker:AddLocations("locations/Guadosalam.json")
Tracker:AddLocations("locations/Inside Sin.json")
Tracker:AddLocations("locations/Kilika.json")
Tracker:AddLocations("locations/Luca.json")
Tracker:AddLocations("locations/Macalania.json")
Tracker:AddLocations("locations/Miihen Highroad.json")
Tracker:AddLocations("locations/Monster Arena.json")
Tracker:AddLocations("locations/Moonflow.json")
Tracker:AddLocations("locations/Mt. Gagazet.json")
Tracker:AddLocations("locations/Mushroom Rock Road.json")
Tracker:AddLocations("locations/Omega Ruins.json")
Tracker:AddLocations("locations/Overdrives.json")
Tracker:AddLocations("locations/Party Member.json")
Tracker:AddLocations("locations/Remiem Temple.json")
Tracker:AddLocations("locations/S.S. Liki.json")
Tracker:AddLocations("locations/S.S. Winno.json")
Tracker:AddLocations("locations/Spira.json")
Tracker:AddLocations("locations/Super Bosses.json")
Tracker:AddLocations("locations/Thunder Plains.json")
Tracker:AddLocations("locations/Zanarkand.json")