
-- Archipelago:AddClearHandler("clear handler", onClear)
Archipelago:AddClearHandler("clear handler", onClearHandler)
Archipelago:AddItemHandler("item handler", onItem)
Archipelago:AddLocationHandler("location handler", onLocation)

Archipelago:AddSetReplyHandler("notify handler", onNotify)
Archipelago:AddRetrievedHandler("notify launch handler", onNotifyLaunch)

-- Region Watches
ScriptHost:AddWatchForCode("update access levels: airship", "airship", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: airshipsin", "airshipsin", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: baajtemple", "baajtemple", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: baajtemple2", "baajtemple2", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: besaid", "besaid", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: bevelle", "bevelle", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: bikanel", "bikanel", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: calmlands", "calmlands", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: cavernofthestolenfayth", "cavernofthestolenfayth", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: djose", "djose", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: gagazet", "gagazet", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: guadosalam", "guadosalam", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: kilika", "kilika", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: luca", "luca", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: macalania", "macalania", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: miihenhighroad", "miihenhighroad", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: moonflow", "moonflow", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: mushroomrockroad", "mushroomrockroad", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: omegaruins", "omegaruins", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: sin", "sin", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: superbosses", "superbosses", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: thunderplains", "thunderplains", UpdateAccessLevels)
ScriptHost:AddWatchForCode("update access levels: zanarkand", "zanarkand", UpdateAccessLevels)

-- Logic Difficulty Watch
ScriptHost:AddWatchForCode("Update Region Access Table", "logicdifficulty", UpdateAccessRegions)